# TODO: fix
FROM node:22

# Create app directory
WORKDIR /app

# Copy Astro project files
COPY ./readers-frontend /app

# Install dependencies and build
RUN npm install
RUN npm run build -- --config astro.config.prod.ts

# Expose the Astro port
EXPOSE 4321

# Run the Astro server
CMD ["node", "dist/server/entry.mjs"]
