# --- Build stage ---
FROM node:22-slim AS build

WORKDIR /app

# Copy Astro project
COPY ./readers-frontend /app

ARG PUBLIC_API_BASE_URL
ARG PUBLIC_BASE_URL
ENV PUBLIC_API_BASE_URL=$PUBLIC_API_BASE_URL
ENV PUBLIC_BASE_URL=$PUBLIC_BASE_URL
ENV NODE_ENV=production
ENV PORT=4321
ENV HOST=0.0.0.0

# Install deps and build
RUN npm install --omit=dev
RUN npm run build -- --config astro.config.prod.ts

EXPOSE 4321

CMD ["node", "dist/server/entry.mjs"]
