# TODO: fix
FROM node:22

# Create app directory
WORKDIR /app

# Copy Astro project files
COPY ./readers-frontend /app

# Install dependencies and build
#RUN npm install
#RUN npx prisma generate
#RUN npm run build --

# Expose the Astro port
EXPOSE 4321

ENV HOST=0.0.0.0

# Run the Astro server
CMD ["node", "dist/server/entry.mjs"]
