-- Insert defaults
INSERT INTO nouse.positionsGroups (`positionsGroups_id`, `positionsGroups_name`, `positionsGroups_actions`) VALUES (1,'Administrator','11,12,4,5,6,7,9,10,13,2,3,14,20,30,21,22,40,41,42,15,43,44,45,46,47,48,49,50,51,52,53,54,32,31,33,55,56,57,58');
INSERT INTO nouse.positionsGroups (`positionsGroups_id`, `positionsGroups_name`, `positionsGroups_actions`) VALUES (2,'Managerial Committee','3,11,2,6,20,4,30,21,22,40,44,45,48,49,50,51,52,53,54,32,31,33,57,58');
INSERT INTO nouse.positionsGroups (`positionsGroups_id`, `positionsGroups_name`, `positionsGroups_actions`) VALUES (3,'Editor','2,20,4,30,21,11,40,44,45,49,32,31,33,57,51,50,52');
INSERT INTO positions (`positions_displayName`, `positions_positionsGroups`, `positions_rank`, `positions_teamPageGroup`) VALUES ('Muse Radio Editor', 3, 51, 1);
INSERT INTO positions (`positions_displayName`, `positions_positionsGroups`, `positions_rank`, `positions_teamPageGroup`) VALUES ('Nouse Radio Editor', 3, 52, 1);
INSERT INTO positions (`positions_displayName`, `positions_positionsGroups`, `positions_rank`, `positions_teamPageGroup`) VALUES ('Puzzles Editor', 3, 53, 1);
INSERT INTO positions (`positions_displayName`, `positions_positionsGroups`, `positions_rank`, `positions_teamPageGroup`) VALUES ('Technical Director','1,2,3',35,4);
UPDATE `positions` SET `positions_teamPageGroup` = 3
WHERE `positions_id` = 58;
INSERT INTO `categories` (`categories_id`, `categories_showHome`, `categories_displayName`, `categories_showMenu`, `categories_name`, `categories_showPublic`, `categories_showAdmin`, `categories_featured`, `categories_order`, `categories_nestUnder`, `categories_showSub`, `categories_facebook`, `categories_twitter`, `categories_instagram`, `categories_backgroundColor`, `categories_backgroundColorContrast`, `categories_customTheme`, `categories_socialMediaOverlay`) VALUES
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ('3621', '0', 'College Sport', '1', 'college-sport', '1', '1', NULL, NULL, '7', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ('3622', '0', 'University Sport', '1', 'university-sport', '1', '1', NULL, NULL, '7', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ('3623', '0', 'National Sport', '1', 'national-sport', '1', '1', NULL, NULL, '7', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ('3624', '0', 'Poetry', '1', 'poetry', '1', '1', NULL, NULL, '3618', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ('3625', '0', 'Prose', '1', 'prose', '1', '1', NULL, NULL, '3618', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ('3626', '0', 'Interviews', '1', 'features-interviews', '1', '1', NULL, NULL, '8', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ('3627', '0', 'Eating locally', '1', 'eating-locally', '1', '1', NULL, NULL, '169', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ('3628', '0', 'Music Interviews', '1', 'music-interviews', '1', '1', NULL, NULL, '24', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `s3files` (`s3files_id`, `s3files_path`, `s3files_filename`, `s3files_extension`, `s3files_original_name`, `s3files_region`, `s3files_endpoint`, `s3files_cdn_endpoint`, `s3files_bucket`, `s3files_compressed`, `s3files_meta_size`, `s3files_meta_public`, `s3files_meta_type`, s3files_meta_uploaded, `s3files_meta_physicallyStored`)
    VALUE (1, 'db/webUploads/public/ARTICLE-THUMBNAIL', '1750089812382-88602768069951200000-1224434610845949882308974206644579337500187ojpgpng', 'png', '12244346_1084594988230897_4206644579337500187_o.jpg.png', 'eu-central-003', 's3.eu-central-003.backblazeb2.com', 'https://bbcdn.nouse.co.uk/file/nousePublicBackendUploads', 'nousePublicBackendUploads', 1, 57596, 1, 3, '2025-06-16 16:03:45', 1);
INSERT INTO `articles` (articles_id, articles_published, articles_showInLists, articles_showInSearch, articles_showInAdmin, articles_type, articles_slug, articles_thumbnail, articles_lifetimeViews, articles_socialConfig)
    VALUE (1, '2025-06-16 15:59:19', 1, 1, 1, 6, 'testing', 1, 0, '1,1,1,1');
INSERT INTO `categories` (categories_id, categories_showHome, categories_displayName, categories_showMenu, categories_name, categories_showPublic, categories_showAdmin, categories_featured, categories_order, categories_nestUnder, categories_showSub, categories_facebook, categories_twitter, categories_instagram, categories_backgroundColor, categories_backgroundColorContrast, categories_customTheme, categories_socialMediaOverlay) VALUE (2,1,'News',1,'news',1,1,'1',1, NULL,1, NULL, NULL, NULL, '#173B88', 'ffffff', NULL, 'news');
INSERT INTO `articlesCategories` (articles_id, categories_id) VALUE (1, 2);
INSERT INTO `users` (`users_name1`, `users_name2`, `users_userid`, `users_changepass`, `users_suspended`) VALUE ('Test', 'Testing', 1, 0, 0);
INSERT INTO `articlesAuthors` (articles_id, users_userid) VALUE (1, 1);
INSERT INTO `articlesDrafts` (articles_id, articlesDrafts_timestamp, articlesDrafts_userid, articlesDrafts_headline, articlesDrafts_excerpt, articlesDrafts_text, articlesDrafts_markdown, articlesDrafts_thumbnailCredit) VALUE (1, '2025-06-16 17:54:18',1,'testing','testing', '<p>testing</p>','testing', 'Nouse');
INSERT INTO `featuredHome` (featuredHome_articles, users_userid) VALUE (1, 1);
INSERT INTO `editions` (editions_id, editions_name, editions_slug, editions_show, editions_showHome, editions_thumbnail, editions_type) VALUE (1, 'Test edition', 'test', 1, 1, 1, 'Print Edition');