{
 "title": "Home",
 "description": "Main Dashboard for Nouse.co.uk",
 "time": { "from": "2019-01-01T00:00:00.000Z", "to": "now" },
 "panels": [
  {
   "title": "Welcome",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Nouse Grafana\n\nWelcome to the Nouse Grafana Site, which enables you to visualise data from our database, such as reads of articles\n\nIt's run by our Technical Directors, so get in touch with them if there's any more graphs/data you'd like to see!"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  articles_published AS \"time\",\n  articles_id\nFROM articles\nWHERE\n  $__timeFilter(articles_published)\nORDER BY articles_published"
    }
   ]
  },
  {
   "title": "Number of Articles Published",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(articles_published,$__interval),\n  count(articles_id) AS \"articles_id\"\nFROM articles\nWHERE\n  $__timeFilter(articles_published) AND\n  articles_showInLists = '1'\nGROUP BY 1\nORDER BY $__timeGroup(articles_published,$__interval)"
    }
   ]
  },
  {
   "title": "Articles Published on Nouse by Month",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(articles_published,1M),\n  count(articles_id)\nFROM articles\nWHERE\n  $__timeFilter(articles_published)\nGROUP BY 1\nORDER BY $__timeGroup(articles_published,1M)"
    }
   ]
  },
  {
   "title": "Article Reads by Hour",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(articlesReads_timestamp,$__interval),\n  count(articles_id) AS \"articleReads_id\"\nFROM articlesReads\nWHERE\n  $__timeFilter(articlesReads_timestamp)\nGROUP BY 1\nORDER BY $__timeGroup(articlesReads_timestamp,$__interval)"
    }
   ]
  },
  {
   "title": "Comments posted on the site",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(comments_created,$__interval),\n  count(comments_id) AS \"comments_id\"\nFROM comments\nWHERE\n  $__timeFilter(comments_created)\nGROUP BY 1\nORDER BY $__timeGroup(comments_created,$__interval)"
    }
   ]
  },
  {
   "title": "Comments posted on the site",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(comments_created,$__interval),\n  count(comments_id) AS \"comments_id\"\nFROM comments\nWHERE\n  $__timeFilter(comments_created) AND\n  (comments_approved = 1 OR comments_approved = 2 OR comments_approved = 3 OR comments_approved =5)\nGROUP BY 1\nORDER BY $__timeGroup(comments_created,$__interval)"
    }
   ]
  }
 ]
}