version: "3.8"

services:
  nouse:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "8.1"
        NODE_VERSION: "none"

    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    restart: always
    depends_on:
      - db
    environment:
      - MYSQL_HOSTNAME=db
      - MYSQL_DATABASE=nouse
      - MYSQL_USER=userDocker
      - MYSQL_PASSWORD=passDocker
    env_file:
      - nouseprod-local.env
    ports:
      - 8080:80
      - 8081:443
  db:
    image: index.docker.io/mysql/mysql-server:8.0
    command: --default-authentication-plugin=mysql_native_password --innodb-thread-concurrency=0 --sort_buffer_size=512K
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - ./docker/mysql:/etc/mysql/conf.d
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=nouse
      - MYSQL_ROOT_HOST=127.0.0.1
      - MYSQL_USER=userDocker
      - MYSQL_PASSWORD=passDocker
      - MYSQL_ROOT_PASSWORD=rootPass
    env_file:
      - nouseprod-local.env
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1
    container_name: phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_ARBITRARY=1
      - PMA_USER=userDocker
      - PMA_PASSWORD=passDocker
    restart: always
    ports:
      - 800:80
    depends_on:
      - db
    volumes:
      - /sessions
  compressor:
      image: ghcr.io/yorknouse/image-compressor:latest
      restart: unless-stopped
      depends_on:
        - db
      environment:
        - MYSQL_HOSTNAME=db
        - MYSQL_DATABASE=nouse
        - MYSQL_USER=userDocker
        - MYSQL_PASSWORD=passDocker
        - SLEEP_TIME=60
      env_file:
        - nouseprod-local.env
volumes:
  db_data: { }